apiVersion: v1
kind: Pod
metadata:
  name: trainer
  namespace: self-supervised-rl-minecraft
  labels:
    app.kubernetes.io/name: training-stcngurs
spec:
  containers:
    - image: immortex/self-supervised-rl-minecraft:trainer
      name: trainer
      imagePullPolicy: Always
      resources:
        requests:
          nvidia.com/gpu: "1"
        limits:
          nvidia.com/gpu: "1"

      ports:
        - containerPort: 9002
          name: http-trainer


  restartPolicy: Never